nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
    # paths:
        # '^/api/': # Chemin de votre API Platform
            # allow_credentials: true
            # allow_origin: ['https://test.reseauh10.fr']
            # allow_headers: ['X-Requested-With', 'Content-Type', 'Authorization']
            # allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
